<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class () extends Migration {
    public function up(): void
    {
        Schema::create('identity_directory', function (Blueprint $table): void {
            $table->uuid('id')->primary(); // UUID generated by HasUuids before insert
            $table->string('identifier_type', 20);
            $table->string('identifier', 255);
            $table->uuid('tenant_id');
            $table->timestampTz('created_at')->useCurrent();

            $table->unique(['identifier', 'tenant_id']);
            $table->index('tenant_id');

            $table->foreign('tenant_id')
                ->references('id')
                ->on('tenants')
                ->cascadeOnDelete();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('identity_directory');
    }
};
